---
- hosts: linux1
  become: yes

  vars:
    mysql_root_password: 12345678

  tasks:
    - name: install mysql
      apt:
        name: mysql-server
        update_cache: yes
        cache_valid_time: 3600
        state: present
    
    - name: install install python-pymysql
      apt:
        name: python-pymysql
        update_cache: yes
        cache_valid_time: 3600
        state: present

    - name: startup mysql service
      shell: "service mysql start"

    - name: enable mysql on boot
      service:
        name: mysql
        state: started
        enabled: true

    - debug:
        msg: "{{ ansible_hostname }}"

    - name: update mysql root passwd
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
        - 172.17.3.240
    - name: create a new database
      mysql_db:
        name: testdb
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
    
    - name: add data to database
      copy: src=notesdb.sql dest=/tmp/notesdb.sql

    - name: insert sample data into database
      mysql_db:
        name: testdb
        state: import
        target: /tmp/notesdb.sql
        login_user: root
        login_password: "{{ mysql_root_password }}"
